FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

WORKDIR /app

# Copia apenas o necessário
COPY requirements-worker.txt .

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libnss3 \
        libnspr4 \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libcups2 \
        libdrm2 \
        libdbus-1-3 \
        libxkbcommon0 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxrandr2 \
        libgbm1 \
        libasound2 \
        libatspi2.0-0 \
        libxshmfence1 \
        ca-certificates \
        fonts-liberation \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --upgrade pip \
    && pip install -r requirements-worker.txt \
    && playwright install chromium \
    && useradd --create-home --shell /bin/bash celeryuser \
    && chown -R celeryuser:celeryuser /app /ms-playwright

COPY . .

USER celeryuser

CMD ["celery", "-A", "pokepricebr", "worker", "--loglevel=info", "--concurrency=2"]
