# Generated by Django 5.2 on 2025-12-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_liga', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('total_set', models.IntegerField()),
                ('numero_completo', models.CharField(max_length=20)),
                ('liga_num', models.CharField(max_length=10)),
                ('raridade', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.set')),
            ],
        ),
    ]
