# Generated by Django 5.2 on 2025-12-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_preco_max_card_preco_med_card_preco_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='liga_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='preco_max_foil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='preco_med_foil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='preco_min_foil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
