# Generated by Django 5.2 on 2025-12-29 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='preco_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='preco_med',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='preco_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='liga_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='raridade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='cards.set'),
        ),
        migrations.AlterField(
            model_name='card',
            name='total_set',
            field=models.PositiveIntegerField(),
        ),
    ]
