# Generated by Django 5.2 on 2025-12-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_liga_url_card_preco_max_foil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
