# Generated by Django 5.2 on 2026-01-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cardadminlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='tcgdex_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
