# Generated by Django 5.2 on 2026-01-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_card_preco_max_master_ball_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='codigo_liga',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
