# Generated by Django 5.2 on 2026-01-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_set_codigo_liga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='codigo_liga',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='tcgdex_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
