# Generated by Django 5.2 on 2026-01-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_set_codigo_liga_alter_set_tcgdex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ilustrador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
