# Generated by Django 5.2 on 2026-01-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_ilustrador_alter_card_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='detalhes_atualizados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='imagem_grande',
            field=models.URLField(blank=True, null=True),
        ),
    ]
