# Generated by Django 5.2 on 2026-02-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_collection_collectioncard'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['set', 'ativa'], name='cards_card_set_id_731888_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['raridade'], name='cards_card_raridad_6e60af_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['tcgdex_id'], name='cards_card_tcgdex__79d591_idx'),
        ),
    ]
