# Generated by Django 5.2 on 2026-02-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_card_cards_card_set_id_731888_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_updating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
