# Generated by Django 5.2 on 2026-02-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_dedupe_set_tcgdex_id_and_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcgdex_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
