# Generated by Django 5.2 on 2026-02-27 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_series_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_covers', to='cards.card'),
        ),
    ]
