# Generated by Django 5.2 on 2026-03-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_collection_cover_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_options/'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
