# Generated by Django 5.2 on 2026-03-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_avatar_image_upload_alter_avatar_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='possui_foil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='possui_master_ball',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='possui_normal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='possui_pokeball_foil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='possui_reverse_foil',
            field=models.BooleanField(default=False),
        ),
    ]
